### ISSUE TITLE
Release v1.2 to NPM

### ISSUE THREAD

**Issue by NicolaiSchmid** [Pranomvignesh/constrained-editor-plugin#10]
Good evening, 

thank you for this amazing project! 

It seems as though version 1.2.0 has not been released to NPM, is that on purpose? 

I'm still stuck on the `onDidChangeContentFast` bug.

Thanks again and best,
Nicolai

**Comment by Pranomvignesh** [comment]
Hi @NicolaiSchmid,
I forgot to publish that version to npm 
Thanks for pointing it out.
Version 1.2.0 is now available in npm [v1.2.0](https://www.npmjs.com/package/constrained-editor-plugin)

**Comment by NicolaiSchmid** [comment]
It works now, thank you very much!
