### ISSUE TITLE
Can I make non editable code hidden?

### ISSUE THREAD

**Issue by tpoxa** [Pranomvignesh/constrained-editor-plugin#11]
Hey.  Thanks for the plugin!

I have some challenges to solve. Please check code above

```ts
function onMessage(msg={name: "", age: 0, arr: [ {k:1}, {k:2}],sub: {test: 32}}): StateObject {
    return {
        CapitalCity: "22",
        Population: msg.arr[0].k,
        ZipCodes:[],
    }
}
```
All looks great like autocompletion of the msg properties. But I really would like to make it look like below:

```ts
function onMessage(msg): StateObject {
    return {
        CapitalCity: "22",
        Population: msg.arr[0].k,
        ZipCodes:[],
    }
}
```
Any chance to do that with this plugin? 
Many thanks in advance!

**Comment by Pranomvignesh** [comment]
Hi @tpoxa ,

I can't understand your use case. Firstly what is an hidden code ?
I'm not sure that Monaco is having a exposed API for hiding the code [Refer this](https://github.com/microsoft/monaco-editor/issues/45)
Moreover, A visible code can be edited so restrictions are needed, but how can an hidden code be edited ?.
