### ISSUE TITLE
No 'UpdateValueInEditableRanges' Method

### ISSUE THREAD

**Issue by HughLK** [Pranomvignesh/constrained-editor-plugin#13]
There's no 'UpdateValueInEditableRanges' method in model object.

**Comment by Pranomvignesh** [comment]
https://github.com/Pranomvignesh/constrained-editor-plugin/blob/f1d48148ae982b4eea3cf98681d6481ea2ca2ef3/src/constrainedModel.js#L539

I have added that method from this line.
Restricted models will have this method.
Kindly recheck whether the model you are trying to access is a restricted model or not

**Comment by HughLK** [comment]
My bad. I somehow installed v1.0.5.  Thanks.
