### ISSUE TITLE
Is there a way to use it with monaco-editor-react?

### ISSUE THREAD

**Issue by shrinidhinhegde** [Pranomvignesh/constrained-editor-plugin#15]

**Comment by Pranomvignesh** [comment]
@shrinidhinhegde I request you to take a look at this issue https://github.com/Pranomvignesh/constrained-editor-plugin/issues/6#issuecomment-1001221794

**Comment by shrinidhinhegde** [comment]
Thanks very much! That solved my problem!

This is really amazing!

PS. Please include this somewhere in the documentation


Thanks
