### ISSUE TITLE
How to use this plugin with monaco-editor react ?

### ISSUE THREAD

**Issue by Deepu1307** [Pranomvignesh/constrained-editor-plugin#22]
https://www.npmjs.com/package/@monaco-editor/react#simple-usage

**Comment by Deepu1307** [comment]
https://www.npmjs.com/package/@monaco-editor/react#simple-usage

**Comment by Pranomvignesh** [comment]
@Deepu1307 I request you to take a look at this issue https://github.com/Pranomvignesh/constrained-editor-plugin/issues/6#issuecomment-1001221794
