### ISSUE TITLE
Is there an implementation available for React?

### ISSUE THREAD

**Issue by NicolaLovo** [Pranomvignesh/constrained-editor-plugin#24]
I am using [Monaco editor react](https://www.npmjs.com/package/@monaco-editor/react) to use the monaco editor in my react project. I am intrested into adding freezed ranges(non-editable ranges) in my editor and I have found your plugin, however I am not able to use it in a React component. Is there a way to do that, or maybe there is another similar package?

**Comment by Pranomvignesh** [comment]
Hi @NicolaLovo I have updated the readme of this repository

You can find the sample code [here](https://github.com/Pranomvignesh/constrained-editor-plugin#sample-code-for-monaco-editorreact)

You can also refer similar duplicate closed issues for monaco editor react [here](https://github.com/Pranomvignesh/constrained-editor-plugin/issues?q=is%3Aissue+React)

**Comment by Pranomvignesh** [comment]
@NicolaLovo, I request you to close this issue once you are satisfied with your answer

**Comment by NicolaLovo** [comment]
@Pranomvignesh Thank you for the answer, sorry for having missed out that part of the documentation.
