### ISSUE TITLE
Able to change the highlighted areas

### ISSUE THREAD

**Issue by johannesfritsch** [Pranomvignesh/constrained-editor-plugin#4]
Hey! Very good job with your implementiation. It seems really solid. But still I found a way to change the highlighted sections:

https://www.youtube.com/watch?v=MhQWv1Gmnr4

To reproduce: Click into an editable area. Press Cmd+A, then press backspace.

Environment: Mac OS Big Sur + Chrome latest

**Comment by Pranomvignesh** [comment]
@johannesfritsch Thanks for reporting the issue.

Highlight is given for developers to make sure that their range configuration is properly working, and here I think the range restrictions are working fine and only the highlighted lines are having mismatch.

I will fix this soon
