### ISSUE TITLE
note on how to use with react-monaco-editor

### ISSUE THREAD

**Issue by garfieldnate** [Pranomvignesh/constrained-editor-plugin#41]
I think it's fairly common to use Monaco in its react form, as I am now. Looking through your documentation, there's no quick-start for applying the plugin to a `<MonacoEditor/>` JSX element. This would make using it a lot easier in this context.

**Comment by Pranomvignesh** [comment]
@garfieldnate I've included the sample code from one of the user in the readme file - [Link](https://github.com/Pranomvignesh/constrained-editor-plugin/blob/master/readme.md#sample-code-for-monaco-editor-react)

Hope this helps

**Comment by garfieldnate** [comment]
@Pranomvignesh That's wonderful, thank you! I was in no way expecting you to immediately get that done. Thank you so much for sharing your project and putting so much love into it!
