### ISSUE TITLE
Help with Angular 14

### ISSUE THREAD

**Issue by nchandarr** [Pranomvignesh/constrained-editor-plugin#59]
### Need sample code snippets to use in angular 14

**Comment by Guzz7** [comment]
Something like this will work.

`import * as constrainedPlugin from "constrained-editor-plugin";

@Component({
  selector: "app-code-editor",
  template: `<ngx-monaco-editor
    [(ngModel)]="textContent"
    (onInit)="handleEditorInit($event)"
  ></ngx-monaco-editor>`,
})
export class CosmosCodeEditorComponent {
  textContent = "";

  handleEditorInit(monacoInstance) {
    const monacoModel = monacoInstance.getModel();

    const constrainedInstance = constrainedPlugin.constrainedEditor(
      window["monaco"]
    );

    constrainedInstance.initializeIn(monacoInstance);

    const restrictions = [
      {
        range: [1, 1, 1, 1],
        label: "restriction1",
        allowMultiline: false,
      },
    ];

    constrainedInstance.addRestrictionsTo(monacoModel, restrictions);
    monacoModel.toggleHighlightOfEditableAreas();
  }
}
`

**Comment by Guzz7** [comment]
import * as constrainedPlugin from "constrained-editor-plugin";
    
    @Component({
      selector: "app-code-editor",
      template: `
        <ngx-monaco-editor
          [(ngModel)]="textContent"
          (onInit)="handleEditorInit($event)"
        ></ngx-monaco-editor>
      `,
    })
    export class CodeEditorComponent {
      textContent = [
        "Blocked section...",
        "Editable section: // Type here",
      ].join("\n");
    
      handleEditorInit(monacoInstance) {
        const monacoModel = monacoInstance.getModel();
    
        const constrainedInstance = constrainedPlugin.constrainedEditor(
          window["monaco"]
        );
    
        constrainedInstance.initializeIn(monacoInstance);
    
        const restrictions = [
          {
            range: [2, 22, 2, 30],
            label: "restriction1",
            allowMultiline: false,
          },
        ];
    
        constrainedInstance.addRestrictionsTo(monacoModel, restrictions);
        monacoModel.toggleHighlightOfEditableAreas();
      }
    }

**Comment by nchandarr** [comment]
Cannot find module 'constrained-editor-plugin' or its corresponding type declarations.

10 import * as constrainedPlugin from 'constrained-editor-plugin';
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                      
I get this when i try to install

**Comment by Guzz7** [comment]
This occurs because the package lacks type declarations (it's pure JavaScript and doesn't include an index.d.ts file). You can refer to this working demo for an example: https://github.com/Guzz7/constrained-editor-angular-example.
