### ISSUE TITLE
Change editor value from code while restrictions exist

### ISSUE THREAD

**Issue by tqwewe** [Pranomvignesh/constrained-editor-plugin#8]
Is there any clean way to change the editor value from code while restrictions are in place? When I try to do so, it immediately gets reset by the constrained instance, and I cannot edit the value.

I managed to do it by:
1. Save existing restriction ranges
    ```js
    const range = constrainedInstance._uriRestrictionMap[model?.uri].getCurrentEditableRanges().state.range;
    ```

2. Remove restrictions
    ```js
    constrainedInstance.removeRestrictionsIn(model);
    ```

3. Update value
    ```js
    setEditorValue(newValue); // React value
    ```

4. Reapply restrictions from previously saved value
    ```js
    constrainedInstance.addRestrictionsTo(model, [
      {
        range: [
          range.startLineNumber,
          range.startColumn,
          range.endLineNumber,
          range.endColumn,
        ],
        label: "state",
        allowMultiline: true,
      },
    ]);
    ```
    
    But I am wondering if there's a better way, as my approach is a little hacky. Thanks!

**Comment by Pranomvignesh** [comment]
@tqwewe There are two cases in altering the editor value

1. Changing the entire editor value ( let us assume, you want to break the existing blueprint structure and have a new structure)
2. Replacing a new content in the current restricted area alone without changing the base blueprint

To achieve the first case, I would advise you to create a new model with that blueprint and just replace that model in the editor instance.

To achieve the second case, There is an method present in the constrained editor plugin : [updateRestrictions](https://constrained-editor-plugin.vercel.app/docs/AvailableAPI/monaco-editor-model-api#updaterestrictions). As I have the track of the range of the current restricted area, This method will update the value in that range.For this to work properly you have to provide a label to uniquely identify the restricted range.

_PS : I guess this method's name is slightly ambiguous, I will change it to `updateValueInRestrictedArea` in the upcoming versions_

I hope this helps you

**Comment by tqwewe** [comment]
Thanks for all the info! I'll try it out shortly.

>  I guess this method's name is slightly ambiguous, I will change it to updateValueInRestrictedArea in the upcoming versions

I see on the documentation it says under `updateRestrictions`:
> update the contents inside the editable ranges

`updateValueInRestrictedArea` sounds like you edit text **outside** the allowed editable area, but I think you mean it should update text in an editable area? Perhaps `updateValueInEditableArea` might be clearer?

**Comment by Pranomvignesh** [comment]
@tqwewe Thanks for the suggestion
> Perhaps updateValueInEditableArea might be clearer

Yes, this seems more clear
